<?xml version="1.0" encoding="utf-8"?><Database Name="ECommerce" Class="ECommerceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Product_ProductDetail" Member="ProductDetails" ThisKey="Id" OtherKey="ProductId" Type="ProductDetail" />
    </Type>
  </Table>
  <Table Name="dbo.ProductDetail" Member="ProductDetails">
    <Type Name="ProductDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Variant" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Product_ProductDetail" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.PR_Product_Delete" Method="PR_Product_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_ProductDetail_Update" Method="PR_ProductDetail_Update">
    <Parameter Name="productid" Type="System.Int32" DbType="Int" />
    <Parameter Name="size" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="variant" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="color" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="costprice" Type="System.Decimal" DbType="Decimal(7,2)" />
    <Parameter Name="saleprice" Type="System.Decimal" DbType="Decimal(7,2)" />
    <Parameter Name="images" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_ProductDetail_Delete" Method="PR_ProductDetail_Delete">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_ProductDetail_SelectAll" Method="PR_ProductDetail_SelectAll">
    <ElementType Name="PR_ProductDetail_SelectAllResult">
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Variant" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_Product_Insert" Method="PR_Product_Insert">
    <Parameter Name="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="model" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="category" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="brand" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="manufacturer" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="size" Type="System.String" DbType="NVarChar(10)" />
    <Parameter Name="variant" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="color" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="description" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="costprice" Type="System.Decimal" DbType="Decimal(7,2)" />
    <Parameter Name="saleprice" Type="System.Decimal" DbType="Decimal(7,2)" />
    <Parameter Name="Images" Parameter="images" Type="System.String" DbType="NVarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.PR_Product_SelectAll" Method="PR_Product_SelectAll">
    <ElementType Name="PR_Product_SelectAllResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_ProductDetails_SelectByPk" Method="PR_ProductDetails_SelectByPk">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_ProductDetails_SelectByPkResult">
      <Column Name="ProductId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Variant" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.PR_Product_SelectByPK" Method="PR_Product_SelectByPK">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_Product_SelectByPKResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Model" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Manufacturer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Size" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Variant" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="CostPrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="SalePrice" Type="System.Decimal" DbType="Decimal(7,2)" CanBeNull="true" />
      <Column Name="Images" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>